### ISSUE TITLE
Is it possible to get these bindings working on Windows with Esy?

### ISSUE THREAD

**Issue by mnxn** [pdonadeo/ocaml-lua#15]
Hi, I'm trying to make a project in OCaml on windows, using the https://esy.sh package manager which works with dune. When it tries to build this project, it understandably fails on `./configure`.

I really like the language OCaml, and this is the only thing stopping me from porting one of my projects over. That project used the following functions from the C api:

`luaL_traceback`
`lua_tostring`
`lua_remove`
`luaL_newstate`
`luaL_openlibs`
`luaL_loadbuffer`
`lua_close`
`lua_pcall`
`lua_pushcfunction`
`lua_insert`
`lua_gettop`

Is it possible to get these bindings working on windows in this scenario? Or would it be more practical to rewrite the bindings for my specific use case? Any help or advice would be very appreciated.

**Comment by pdonadeo** [comment]
Hi @mnxn the answer here is "I don't know". I have no idea how OCaml on Windows works, how to build a tool chain on that OS and I actually have no access to a Windows box since 20 years.

That said I can still try.

Do you know if some sort of Windows license is available **for free** (sorry I don't want to spend a penny for a Windows license) for open source developers? In that case I can try and install Windows on VirtualBox and try to compile there.

**Comment by mnxn** [comment]
@pdonadeo

You can download the windows iso (https://www.microsoft.com/en-us/software-download/windows10ISO) and run it unactivated. I think all that does is have a watermark in the bottom right after 30 days of not activating it.

Esy setups up the whole toolchain and compiles OCaml from source automatically. You can see an example project at https://github.com/esy-ocaml/hello-ocaml

If you were to add a `@opam/ocaml-lua` dependency to `package.json` and try to build on windows with `esy build`, it's going to error when it tries to call `./configure`. I haven't looked through the whole source of this project but my guess is that to get it to work on windows would probably require rewriting `configure` to something that works on windows.

For my specific use case, I managed to make a single function in C that does all that I want and call it from OCaml, but it would still be nice to have the entire bindings with this library.

**Comment by pdonadeo** [comment]
OK, tomorrow I will download a Windows image and I'll try, but a make no promise: I don't know that world, in particular how to install Lua 5.1 and a C compiler.

Can Esy also install Lua and a C compiler?

**Comment by mnxn** [comment]
I believe Esy comes with cygwin, which comes with gcc that you can call with `x86_64-w64-mingw32-gcc`. It isn't available on the PATH unless you call `esy build x86_64-w64-mingw32-gcc` or launch a new terminal with it on the path: `esy powershell` 

I don't think Esy can install Lua automatically, so what I've been doing is compiling it from source before linking to the library from a `dune` file. You can using make for luajit with `esy build make CROSS=x86_64-w64-mingw32- HOST_CC=x86_64-w64-mingw32-gcc`

I'll try to make a basic Esy project if that might help.

**Comment by mnxn** [comment]
Alright I made a repository that represents more or less what I'm using for Lua right now. 

You can see it here: https://github.com/mnxn/esy-ocaml-lua-example

To try it with `ocaml-lua` you could slightly change `package.json` and `main/dune`:

<details>
 <summary>package.json</summary>

```
{
  "name": "esy-ocaml-lua-example",
  "version": "0.0.1",
  "esy": {
    "build": "dune build -p #{self.name}",
    "buildEnv": {
      "LUAJIT_SRC": "#{self.root}/luajit/src"
    }
  },
  "scripts": {
    "lua-clean": "esy build make -C luajit/src/ CROSS=x86_64-w64-mingw32- HOST_CC=x86_64-w64-mingw32-gcc clean",
    "lua-compile": "esy build make -C luajit/src/ CROSS=x86_64-w64-mingw32- HOST_CC=x86_64-w64-mingw32-gcc BUILDMODE=static"
  },
  "dependencies": {
    "@opam/dune": "*",
    "@opam/ocaml-lua": "*"
    "ocaml": "~4.07.1"
  },
  "devDependencies": {
    "ocaml": "~4.07.1"
  }
}
``` 
</details> 

<details>
 <summary>main/dune</summary>

```
(executable
  (public_name main)
  (name        main)
  (libraries   ocaml-lua))
```
</details>

Then, you should be able to change the contents of `main/main.ml` and follow the directions I wrote in the readme to build it with esy.

**Comment by pdonadeo** [comment]
Windows: exactly as **awful** as I remember...

![virtualbox_windev1811eval_24_02_2019_14_22_33](https://user-images.githubusercontent.com/242049/53299817-dd652800-383f-11e9-8c7a-3e6f0865ebec.png)

**Comment by pdonadeo** [comment]
Hi @mnxn I spent yesterday afternoon trying to compile Lua 5.1.5 in an Esy environment, as you ask. Without any success at all.

There are several serious problems here:
1. Lua 5.1.5 (as opposed to Luajit) can't compile in that env because it requires Unix utilities, like `strip` and `ar`
1. the `ocaml-lua` project is not built with `dune` but with OASIS/ocamlbuild, both of which can't run in Windows
1. more: Esy under that operating system is really unstable and considered "alpha", as you can read here: https://reasonml.github.io/docs/en/native

I'm sorry but in the present situation it's very hard if not impossible what you ask, but I want to try again.

The very first and most important issue to fix is to build the project using dune.

I leave this issue open because I want to keep the project alive and a Windows porting is a long standing requirement.

**Comment by mnxn** [comment]
Hi @pdonadeo thank you for your attempt!

Like `gcc`, `strip` and `ar` should be accessible from `x86_64-w64-mingw32-strip` and `x86_64-w64-mingw32-ar`, respectively. And like `gcc`, they will need to be called from cygwin. Getting Lua to build with those prefixed version will likely involve modifying the Makefile variables, like I mentioned doing with `gcc`.

I looked through the source of `ocaml-lua` and at first glance it doesn't look too hard to port it to dune. I'll try to do it myself when I have some free time.

**Comment by pdonadeo** [comment]
@mnxn I'm sorry but after (yet another) weekend passed trying to compile the project in a reliable way  under Windows I'm going to give up completely.
