### ISSUE TITLE
4.08 compatibility

### ISSUE THREAD

**Issue by kandu** [pdonadeo/ocaml-lua#16]
Hi, dear @pdonadeo 
Since ocaml 4.08 was released, it would be nice to make ocaml-lua compatible with the new release :)

**Comment by pdonadeo** [comment]
@kandu yes, thanks for the reminder. I'm also working to porting the build system to dune.

**Comment by kandu** [comment]
(≧∇≦)b

**Comment by pdonadeo** [comment]
@kandu I just pushed the version 1.8. This is the changelog:

 - Porting to OCaml 4.08.1
 - Build system switch from OASIS to dune
 - Lua 5.1.5 source code included to avoid externals
 - Library public name changes from liblua to ocaml-lua
 - Docs are built with odoc
 - Dropped support for LuaJIT

It also works on OSX, which is reason why you are waiting since many months for this simple update: I do not have an OSX machine.

Now I think I'm supposed to work on #15.

**Comment by kandu** [comment]
@pdonadeo thanks. The curse causing my friend and I stick to 4.06 is now purged by a mage :)
